/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TalameedRouteImport } from './routes/talameed'
import { Route as TaleemRouteImport } from './routes/taleem'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TalameedRoute = TalameedRouteImport.update({
  id: '/talameed',
  path: '/talameed',
  getParentRoute: () => rootRouteImport,
} as any)
const TaleemRoute = TaleemRouteImport.update({
  id: '/taleem',
  path: '/taleem',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/talameed': typeof TalameedRoute
  '/taleem': typeof TaleemRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/talameed': typeof TalameedRoute
  '/taleem': typeof TaleemRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/talameed': typeof TalameedRoute
  '/taleem': typeof TaleemRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/talameed' | '/taleem'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/talameed' | '/taleem'
  id: '__root__' | '/' | '/talameed' | '/taleem'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TalameedRoute: typeof TalameedRoute
  TaleemRoute: typeof TaleemRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/talameed': {
      id: '/talameed'
      path: '/talameed'
      fullPath: '/talameed'
      preLoaderRoute: typeof TalameedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/taleem': {
      id: '/taleem'
      path: '/taleem'
      fullPath: '/taleem'
      preLoaderRoute: typeof TaleemRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TalameedRoute: TalameedRoute,
  TaleemRoute: TaleemRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
